//Error
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//App
export const SET_APPLIACTION_MODULE = "SET_APPLIACTION_MODULE";
export const SET_APP_LOADING = "SET_APP_LOADING";

//Auth
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SET_AUTH_DATA_LOADING = "SET_AUTH_DATA_LOADING";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_EMAIL_UNVERIFIED = "SET_EMAIL_UNVERIFIED";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

//Candidate profile
export const SET_CANDIDATE_DATA_LOADING = "SET_CANDIDATE_DATA_LOADING";
// export const SET_CANDIDATE_CONFIDENT_PROJECT_DATA_LOADING = "SET_CANDIDATE_CONFIDENT_PROJECT_DATA_LOADING";
export const GET_CANDIDATE_DETAILS = "GET_CANDIDATE_DETAILS";
export const CANDIDATE_UPDATE_ACTION_IN_PROGRESS =
	"CANDIDATE_UPDATE_ACTION_IN_PROGRESS";
export const SET_CANDIDATE_GALK_SUBSCRIPTION =
	"SET_CANDIDATE_GALK_SUBSCRIPTION";
export const GET_ACTIVE_FORM_STEP = "GET_ACTIVE_FORM_STEP";
export const GET_USER_PROGRAM = "GET_USER_PROGRAM";
export const GO_NEXT_STEP = "GO_NEXT_STEP";
export const GO_PREV_STEP = "GO_PREV_STEP";

export const START_PROFILE_IMAGE_UPLOAD = "START_PROFILE_IMAGE_UPLOAD";
export const STOP_PROFILE_IMAGE_UPLOAD = "STOP_PROFILE_IMAGE_UPLOAD";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const START_CANDIDATE_DATA_LOADING = "START_CANDIDATE_DATA_LOADING";
export const STOP_CANDIDATE_DATA_LOADING = "STOP_CANDIDATE_DATA_LOADING";
export const DATA_SAVE_PROGRESS = "DATA_SAVE_PROGRESS";
export const DATA_EDIT_IN_PROGRESS = "DATA_EDIT_IN_PROGRESS";

export const UPDATE_VIDEO_UPLOAD_PROGRESS = "UPDATE_VIDEO_UPLOAD_PROGRESS";
export const UPDATE_CANDIDATE_INTROVIDEO = "UPDATE_CANDIDATE_INTROVIDEO";
export const dataSavingState = Object.freeze({
	SAVING: "SAVING",
	SAVED: "SAVED",
	IDLE: "IDLE",
});

//Types for Student
export const GET_ALL_STUDENT_LIST = "GET_ALL_STUDENT_LIST";
export const GET_ALL_THIRD_YEAR_STUDENT_LIST =
	"GET_ALL_THIRD_YEAR_STUDENT_LIST";
export const GET_ALL_FOURTH_YEAR_STUDENT_LIST =
	"GET_ALL_FOURTH_YEAR_STUDENT_LIST";
export const GET_ALL_GRADUATE_STUDENT_LIST = "GET_ALL_GRADUATE_STUDENT_LIST";

export const FILTER_STUDENT_LIST = "FILTER_STUDENT_LIST";
export const FILTER_THIRD_YEAR_STUDENT_LIST = "FILTER_THIRD_YEAR_STUDENT_LIST";
export const FILTER_FOURTH_YEAR_STUDENT_LIST =
	"FILTER_FOURTH_YEAR_STUDENT_LIST";
export const FILTER_GRADUATE_STUDENT_LIST = "FILTER_GRADUATE_STUDENT_LIST";

export const SET_STUDENT_LIST_LOADING = "SET_STUDENT_LIST_LOADING";

export const GET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE =
	"GET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE";
export const SET_STUDENT_TO_SHOW_DETAILS_LOADING_IN_STUDENT_MODULE =
	"SET_STUDENT_TO_SHOW_DETAILS_LOADING_IN_STUDENT_MODULE";
export const RESET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE =
	"RESET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE";
export const SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE =
	"SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE";
export const SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE_GALK_LAB =
	"SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE_GALK_LAB";
export const UPDATE_COMPANY_TAG_IN_STUDENT_MODULE =
	"UPDATE_COMPANY_TAG_IN_STUDENT_MODULE";
export const UPDATE_GALK_LAB_COMPANY_TAG_IN_STUDENT_MODULE =
	"UPDATE_GALK_LAB_COMPANY_TAG_IN_STUDENT_MODULE";
export const SET_SUBSCRIBED_STUDENT = "SET_SUBSCRIBED_STUDENT";
export const SET_UNSUBSCRIBED_STUDENT = "SET_UNSUBSCRIBED_STUDENT";

export const SET_STUDENT_PROFILE_IMG = "SET_STUDENT_PROFILE_IMG";
export const SET_STUDENT_PROFILE_VIDEO = "SET_STUDENT_PROFILE_VIDEO";
export const UPDATE_STUDENT_BASIC_INFORMATION =
	"UPDATE_STUDENT_BASIC_INFORMATION";
export const UPDATE_STUDENT_EDUCATION_INFORMATION =
	"UPDATE_STUDENT_EDUCATION_INFORMATION";
export const UPDATE_STUDENT_JOB_INFORMATION = "UPDATE_STUDENT_JOB_INFORMATION";
export const UPDATE_STUDENT_PROJECT_INFORMATION =
	"UPDATE_STUDENT_PROJECT_INFORMATION";
export const UPDATE_STUDENT_CERTIFICATE_INFORMATION =
	"UPDATE_STUDENT_CERTIFICATE_INFORMATION";
export const UPDATE_STUDENT_EXTRACURRICULAR_INFORMATION =
	"UPDATE_STUDENT_EXTRACURRICULAR_INFORMATION";

//Types for galklab job posting
export const GET_GALKLAB_JOBS = "GET_GALKLAB_JOBS";
export const GALKLAB_JOB_LOADING = "GALKLAB_JOB_LOADING";
export const GALKLAB_JOB_LOADED = "GALKLAB_JOB_LOADED";
export const GALKLAB_JOB_LOAD_ERROR = "GALKLAB_JOB_LOAD_ERROR";
export const GET_GALKLAB_ALL_JOBS = "GET_GALKLAB_ALL_JOBS";

export const GET_GALKLAB_MATCHED_JOBS = "GET_GALKLAB_MATCHED_JOBS";
export const GALKLAB_MATCHED_JOBS_INDEX = "GALKLAB_MATCHED_JOBS_INDEX";
export const GALKLAB_MATCHED_JOBS_LOADING = "GALKLAB_MATCHED_JOBS_LOADING";

export const GALKRECRUIT_ALL_PROJECTS_LOADING = "GALKRECRUIT_ALL_PROJECTS_LOADING";
export const GALKRECRUIT_ALL_PROJECTS_ERROR = "GALKRECRUIT_ALL_PROJECTS_ERROR";
export const GET_GALKRECRUIT_ALL_PROJECTS = "GET_GALKRECRUIT_ALL_PROJECTS";


export const GALKRECRUIT_CONFIDENT_PROJECTS_LOADING = "GALKRECRUIT_CONFIDENT_PROJECTS_LOADING";
export const GALKRECRUIT_CONFIDENT_PROJECTS_ERROR = "GALKRECRUIT_CONFIDENT_PROJECTS_ERROR";
export const GET_GALKRECRUIT_CONFIDENT_PROJECTS = "GET_GALKRECRUIT_CONFIDENT_PROJECTS";


export const GALKRECRUIT_SHORTLISTED_PROJECTS_LOADING = "GALKRECRUIT_SHORTLISTED_PROJECTS_LOADING";
export const GALKRECRUIT_SHORTLISTED_PROJECTS_ERROR = "GALKRECRUIT_SHORTLISTED_PROJECTS_ERROR";
export const GET_GALKRECRUIT_SHORTLISTED_PROJECTS = "GET_GALKRECRUIT_SHORTLISTED_PROJECTS";


export const GALKRECRUIT_SHORTLISTED_PROJECTS_BY_COMPANY_LOADING = "GALKRECRUIT_SHORTLISTED_PROJECTS_BY_COMPANY_LOADING";
export const GALKRECRUIT_SHORTLISTED_PROJECTS_BY_COMPANY_ERROR = "GALKRECRUIT_SHORTLISTED_PROJECTS_BY_COMPANY_ERROR";
export const GET_GALKRECRUIT_SHORTLISTED_PROJECTS_BY_COMPANY = "GET_GALKRECRUIT_SHORTLISTED_PROJECTS_BY_COMPANY";



// Types for Questions printing for internship
export const GET_SCREENING_QUESTIONS = "GET_SCREENING_QUESTIONS";
export const SCREENING_QUESTIONS_LOADING = "SCREENING_QUESTIONS_LOADING";
export const SCREENING_QUESTION_LOAD_ERROR = "SCREENING_QUESTION_LOAD_ERROR";

/// ATTENDANCE TYPES
export const GET_GALKLAB_ATTENDANCE = "GET_GALKLAB_ATTENDANCE";
export const GALKLAB_ATTENDANCE_CHANGE_STATE =
	"GALKLAB_ATTENDANCE_CHANGE_STATE";
export const GALKLAB_ATTENDANCE_UPDATE = "GALKLAB_ATTENDANCE_UPDATE";
export const UPDATE_TIMESHEET_IN_GALKLAB_JOB =
	"UPDATE_TIMESHEET_IN_GALKLAB_JOB";
export const NOTIFICATION_STATES = {
	success: "SUCCESS",
	failed: "FAILED",
	processing: "PROCESSING",
	idle: "IDLE",
};

// types for chat room of GALK LAB
export const GET_AVAILABLE_CHAT_LISTS = "GET_AVAILABLE_CHAT_LISTS";
export const START_CHAT_LIST_LOADING = "START_CHAT_LIST_LOADING";
export const STOP_CHAT_LIST_LOADING = "STOP_CHAT_LIST_LOADING";
export const START_MESSAGE_LOADING = "START_MESSAGE_LOADING";
export const STOP_MESSAGE_LOADING = "STOP_MESSAGE_LOADING";
export const GET_COMPANY_METADATA = "GET_COMPANY_METADATA";
export const GET_STUDENT_METADATA = "GET_STUDENT_METADATA";
export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
export const CLEAR_CHAT_ROOM_DATA = "CLEAR_CHAT_ROOM_DATA";
export const SET_CHAT_FILEUPLOAD_LOADING = "SET_CHAT_FILEUPLOAD_LOADING";
export const SET_CHAT_FILEUPLOAD_PROGRESS = "SET_CHAT_FILEUPLOAD_PROGRESS";

// types for organisation data
export const SET_COLLEGES = "SET_COLLEGES";
export const SET_BRANCHES = "SET_BRANCHES";
export const SET_CERTIFICATE_COURSES = "SET_CERTIFICATE_COURSES";
export const SET_FOODS = "SET_FOODS";
export const SET_RELIGIONS = "SET_RELIGIONS";
export const SET_SKILLS = "SET_SKILLS";
export const SET_SPOKEN_LANGUAGES = "SET_SPOKEN_LANGUAGES";
export const SET_PROJECT_DOMAINS = "SET_PROJECT_DOMAINS";