//Types for Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED";
export const CLEAR_STORE_DATA = "CLEAR_STORE_DATA";
export const SET_AUTH_DATA_LOADING = "SET_AUTH_DATA_LOADING";
export const SET_MENTOR_LOGIN = "SET_MENTOR_LOGIN";
export const SET_USER_TYPE = "SET_USER_TYPE";

//Types for Company User
export const GET_COMPANY_USER_DETAILS = "GET_COMPANY_USER_DETAILS";
export const UPDATE_COMPANY_USER_DETAILS = "UPDATE_COMPANY_USER_DETAILS";
export const COMPANY_USER_DATA_LOADING = "COMPANY_USER_DATA_LOADING";
export const SET_COMPANY_PROFILE_COMPLETE_STATUS =
  "SET_COMPANY_PROFILE_COMPLETE_STATUS";
export const SET_OWN_PROFILE_COMPLETE_STATUS =
  "SET_OWN_PROFILE_COMPLETE_STATUS";

//Types for Language set
export const SET_LANGUAGE = "SET_LANGUAGE";

/********************************************************************************************/

// Types for new company profile

//Types for application module
export const APP_MODULE_LOADING = "APP_MODULE_LOADING";
export const SET_APPLIACTION_MODULE = "SET_APPLIACTION_MODULE";

//Types for Company side
export const GET_ALL_COMPANY_LIST = "GET_ALL_COMPANY_LIST";
export const SET_COMPANY_LIST_LOADING = "SET_COMPANY_LIST_LOADING";
export const RESET_COMPANY_LIST = "RESET_COMPANY_LIST";
export const GET_COMPANY_DETAILS = "GET_COMPANY_DETAILS";
export const SET_COMPANY_DETAILS_LOADING = "SET_COMPANY_DETAILS_LOADING";
export const RESET_COMPANY_DETAILS = "RESET_COMPANY_DETAILS";

export const SET_ACTION_IN_PRROGRESS_FOR_COMPANY_PROFILE =
  "SET_ACTION_IN_PRROGRESS_FOR_COMPANY_PROFILE";
export const SET_COMPANY_PROFILE_LOGO = "SET_COMPANY_PROFILE_LOGO";
export const SET_COMPANY_PROFILE_COVER_PHOTO =
  "SET_COMPANY_PROFILE_COVER_PHOTO";
export const UPDATE_COMPANY_BASIC_INFORMATION =
  "UPDATE_COMPANY_BASIC_INFORMATION";
export const UPDATE_COMPANY_OPERATIONAL_INFORMATION =
  "UPDATE_COMPANY_OPERATIONAL_INFORMATION";
export const UPDATE_ACCOUNT_USER_AUTHORIZATION =
  "UPDATE_ACCOUNT_USER_AUTHORIZATION";
export const ADD_NEW_ACCOUNT_USER = "ADD_NEW_ACCOUNT_USER";

export const GET_INTERNSHIP_JOB_LIST_TO_SHOW =
  "GET_INTERNSHIP_JOB_LIST_TO_SHOW";
export const GET_GALK_JOB_LIST_TO_SHOW = "GET_GALK_JOB_LIST_TO_SHOW";
export const UPDATE_TIMESHEET_IN_GALKLAB_JOB =
  "UPDATE_TIMESHEET_IN_GALKLAB_JOB";
export const SET_INTERNSHIP_JOB_LIST_LOADING =
  "SET_INTERNSHIP_JOB_LIST_LOADING";
export const SET_GALK_JOB_LIST_LOADING = "SET_GALK_JOB_LIST_LOADING";
export const RESET_INTERNSHIP_JOB_LIST = "RESET_INTERNSHIP_JOB_LIST";
export const RESET_GALK_JOB_LIST = "RESET_GALK_JOB_LIST";
export const UPDATE_INTERNSHIP_JOB_TO_SHOW = "UPDATE_INTERNSHIP_JOB_TO_SHOW";
export const UPDATE_GALK_JOB_TO_SHOW = "UPDATE_GALK_JOB_TO_SHOW";
export const DELETE_INTERNSHIP_JOB_TO_SHOW = "DELETE_INTERNSHIP_JOB_TO_SHOW";
export const DELETE_GALK_JOB_TO_SHOW = "DELETE_GALK_JOB_TO_SHOW";
export const ADD_INTERNSHIP_JOB_TO_SHOW = "ADD_INTERNSHIP_JOB_TO_SHOW";
export const ADD_GALK_JOB_TO_SHOW = "ADD_GALK_JOB_TO_SHOW";
export const SET_ACTION_IN_PRROGRESS_FOR_INTERNSHIP_JOB_TO_SHOW =
  "SET_ACTION_IN_PRROGRESS_FOR_INTERNSHIP_JOB_TO_SHOW";
export const SET_ACTION_IN_PRROGRESS_FOR_GALK_JOB_TO_SHOW =
  "SET_ACTION_IN_PRROGRESS_FOR_GALK_JOB_TO_SHOW";
export const SET_INTERNSHIP_JOB_TO_SHOW_STATUS =
  "SET_INTERNSHIP_JOB_TO_SHOW_STATUS";
export const SET_GALK_JOB_TO_SHOW_STATUS = "SET_GALK_JOB_TO_SHOW_STATUS";
export const UPDATE_GALK_LAB_MENTOR_ASSIGNED =
  "UPDATE_GALK_LAB_MENTOR_ASSIGNED";
export const GALK_LAB_MENTOR_ASSIGN_PROCESSING =
  "GALK_LAB_MENTOR_ASSIGNE_PROCESSING";
export const GALK_LAB_MENTOR_ASSIGN_FAILED = "GALK_LAB_MENTOR_ASSIGNE_FAILED";
export const GET_THIRDYEAR_TAGGED_STUDENT_LIST =
  "GET_THIRDYEAR_TAGGED_STUDENT_LIST";
export const GET_GALK_TAGGED_STUDENT_LIST = "GET_GALK_TAGGED_STUDENT_LIST";
export const SET_THIRDYEAR_TAGGED_STUDENT_LIST_LOADING =
  "SET_THIRDYEAR_TAGGED_STUDENT_LIST_LOADING";
export const SET_GALK_TAGGED_STUDENT_LIST_LOADING =
  "SET_GALK_TAGGED_STUDENT_LIST_LOADING";
export const REQUEST_INTERVIEW_FOR_THIRD_YEAR =
  "REQUEST_INTERVIEW_FOR_THIRD_YEAR";
export const REMOVE_GALKLAB_STUDENT_TAG = "REMOVE_GALKLAB_STUDENT_TAG";
export const SET_GALKLAB_STUDENT_ACTION_IN_PROGRESS =
  "SET_GALKLAB_STUDENT_ACTION_IN_PROGRESS";

export const GET_INTERVIEW_PANEL_LIST = "GET_INTERVIEW_PANEL_LIST";
export const SET_INTERVIEW_PANEL_LIST_LOADING =
  "SET_INTERVIEW_PANEL_LIST_LOADING";
export const SET_INTERVIEW_PANEL_ACTION_IN_PROGRESS =
  "SET_INTERVIEW_PANEL_ACTION_IN_PROGRESS";
export const SELECT_STUDENT_FOR_THIRD_YEAR = "SELECT_STUDENT_FOR_THIRD_YEAR";
export const SELECT_STUDENT_FOR_FOURTH_YEAR = "SELECT_STUDENT_FOR_FOURTH_YEAR";
export const SELECT_STUDENT_FORM_INTERVIEW_PANEL =
  "SELECT_STUDENT_FORM_INTERVIEW_PANEL";

export const GET_STUDENT_TO_SHOW_DETAILS = "GET_STUDENT_TO_SHOW_DETAILS";
export const SET_STUDENT_TO_SHOW_DETAILS_LOADING =
  "SET_STUDENT_TO_SHOW_DETAILS_LOADING";
export const RESET_STUDENT_TO_SHOW_DETAILS = "RESET_STUDENT_TO_SHOW_DETAILS";
export const SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS =
  "SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS";
export const SET_GALK_STUDENT_TO_SHOW_ACTION_IN_PROGRESS =
  "SET_GALK_STUDENT_TO_SHOW_ACTION_IN_PROGRESS";
export const UPDATE_GALK_LAB_JOB_ASSIGNED = "UPDATE_GALK_LAB_JOB_ASSIGNED";
export const SET_THIRD_YEAR_STUDENT_META = "SET_THIRD_YEAR_STUDENT_META";

//Company types for GALK lab students
export const GET_GALK_INTERVIEW_PANEL_LIST = "GET_GALK_INTERVIEW_PANEL_LIST";
export const SELECT_GALK_STUDENT_FORM_INTERVIEW_PANEL =
  "SELECT_GALK_STUDENT_FORM_INTERVIEW_PANEL";
export const REQUEST_INTERVIEW_FOR_GALK_LAB = "REQUEST_INTERVIEW_FOR_GALK_LAB";

//GalkLab student
export const GALKLAB_GET_STUDENT_LIST = "GALKLAB_GET_STUDENT_LIST";
export const GALKLAB_SET_STUDENT_LIST_LOADING =
  "GALKLAB_SET_STUDENT_LIST_LOADING";
export const GALKLAB_GET_STUDENT_TO_SHOW_DETAILS =
  "GALKLAB_GET_STUDENT_TO_SHOW_DETAILS";
export const GALKLab_GET_STUDENT_TO_SHOW_DETAILS =
  "GALKLab_GET_STUDENT_TO_SHOW_DETAILS";
export const GALKLAB_SET_STUDENT_TO_SHOW_DETAILS_LOADING =
  "GALKLAB_SET_STUDENT_TO_SHOW_DETAILS_LOADING";
export const GALKLAB_RESET_STUDENT_TO_SHOW_DETAILS =
  "GALKLAB_RESET_STUDENT_TO_SHOW_DETAILS";
export const GALKLab_FILTER_THIRD_YEAR_STUDENTS =
  "GALKLab_FILTER_THIRD_YEAR_STUDENTS";
export const GALKLab_SET_ACTION_IN_PRROGRESS_FOR_THIRD_YEAR =
  "GALKLab_SET_ACTION_IN_PRROGRESS_FOR_THIRD_YEAR";
export const GALKLab_REQUEST_INTERVIEW_FOR_THIRD_YEAR =
  "GALKLab_REQUEST_INTERVIEW_FOR_THIRD_YEAR";
export const UPDATE_GALK_LAB_JOB_ASSIGNED_ENGINEER =
  "UPDATE_GALK_LAB_JOB_ASSIGNED_ENGINEER";
export const UPDATE_GALK_LAB_JOB_ASSIGN_PORCESSING =
  "UPDATE_GALK_LAB_JOB_ASSIGN_PORCESSING";
export const UPDATE_GALK_LAB_JOB_UNASSIGNED = "UPDATE_GALK_LAB_JOB_UNASSIGNED";
//Types for Student
export const GET_ALL_STUDENT_LIST = "GET_ALL_STUDENT_LIST";
export const GET_ALL_THIRD_YEAR_STUDENT_LIST =
  "GET_ALL_THIRD_YEAR_STUDENT_LIST";
export const GET_ALL_FOURTH_YEAR_STUDENT_LIST =
  "GET_ALL_FOURTH_YEAR_STUDENT_LIST";
export const GET_ALL_GRADUATE_STUDENT_LIST = "GET_ALL_GRADUATE_STUDENT_LIST";

export const FILTER_STUDENT_LIST = "FILTER_STUDENT_LIST";
export const FILTER_THIRD_YEAR_STUDENT_LIST = "FILTER_THIRD_YEAR_STUDENT_LIST";
export const FILTER_FOURTH_YEAR_STUDENT_LIST =
  "FILTER_FOURTH_YEAR_STUDENT_LIST";
export const FILTER_GRADUATE_STUDENT_LIST = "FILTER_GRADUATE_STUDENT_LIST";

export const SET_STUDENT_LIST_LOADING = "SET_STUDENT_LIST_LOADING";

export const GET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE =
  "GET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE";
export const SET_STUDENT_TO_SHOW_DETAILS_LOADING_IN_STUDENT_MODULE =
  "SET_STUDENT_TO_SHOW_DETAILS_LOADING_IN_STUDENT_MODULE";
export const RESET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE =
  "RESET_STUDENT_TO_SHOW_DETAILS_IN_STUDENT_MODULE";
export const SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE =
  "SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE";
export const SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE_GALK_LAB =
  "SET_STUDENT_TO_SHOW_ACTION_IN_PROGRESS_IN_STUDENT_MODULE_GALK_LAB";
export const UPDATE_COMPANY_TAG_IN_STUDENT_MODULE =
  "UPDATE_COMPANY_TAG_IN_STUDENT_MODULE";
export const UPDATE_GALK_LAB_COMPANY_TAG_IN_STUDENT_MODULE =
  "UPDATE_GALK_LAB_COMPANY_TAG_IN_STUDENT_MODULE";
export const SET_SUBSCRIBED_STUDENT = "SET_SUBSCRIBED_STUDENT";
export const SET_UNSUBSCRIBED_STUDENT = "SET_UNSUBSCRIBED_STUDENT";

export const SET_STUDENT_PROFILE_IMG = "SET_STUDENT_PROFILE_IMG";
export const SET_STUDENT_PROFILE_VIDEO = "SET_STUDENT_PROFILE_VIDEO";
export const UPDATE_STUDENT_BASIC_INFORMATION =
  "UPDATE_STUDENT_BASIC_INFORMATION";
export const UPDATE_STUDENT_EDUCATION_INFORMATION =
  "UPDATE_STUDENT_EDUCATION_INFORMATION";
export const UPDATE_STUDENT_PROJECT_INFORMATION =
  "UPDATE_STUDENT_PROJECT_INFORMATION";
export const UPDATE_STUDENT_CERTIFICATE_INFORMATION =
  "UPDATE_STUDENT_CERTIFICATE_INFORMATION";
export const UPDATE_STUDENT_EXTRACURRICULAR_INFORMATION =
  "UPDATE_STUDENT_EXTRACURRICULAR_INFORMATION";

//  Admin activity reducer
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED";
export const NOTIFICATION_PROCESSING = "NOTIFICATION_PROCESSING";
export const NOTIFICATION_IDLE = "NOTIFICATION_IDLE";
export const NOTIFICATION_STATES = {
  success: "SUCCESS",
  failed: "FAILED",
  processing: "PROCESSING",
  idle: "IDLE",
};
//// JOB PROGRESS
export const JOB_PROGRESS_LOADING = "JOB_PROGRESS_LOADING";
export const JOB_PROGRESS_OPEN_PULL = "JOB_PROGRESS_OPEN_PULL";
export const JOB_PROGRESS_CLOSED_PULL = "JOB_PROGRESS_CLOSED_PULL";
export const JOB_PROGRESS_OPEN_ISSUES = "JOB_PROGRESS_OPEN_ISSUES";
export const JOB_PROGRESS_CLOSED_ISSUES = "JOB_PROGRESS_CLOSED_ISSUES";
export const JOB_PROGRESS_FAILED = "JOB_PROGRESS_FAILED";
export const ADD_REPO_PROCESSING = "ADD_REPO_PROCESSING";
export const ADD_REPO_SUCCESS = "ADD_REPO_SUCCESS";
export const ADD_REPO_FAILED = "ADD_REPO_FAILED";
export const ADD_REPO_IDLE = "ADD_REPO_IDLE";
export const UPDATE_ADD_REPO_IN_JOB = "UPDATE_ADD_REPO_IN_JOB";
export const TIMELINE_LOADED = "TIMELINE_LOADED";
export const BODY_LOADED = "BODY_LOADED";
export const ISSUE_LOADING = "ISSUE_LOADING";
export const RESET_TIMELINE = "RESET_TIMELINE";
export const RESET_ERROR = "RESET_ERROR";

// MENTOR PAGE
export const GALKLAB_JOB_LOADING_MENTOR = "GALKLAB_JOB_LOADING";
export const GET_GALKLAB_JOBS_MENTOR = "GET_GALKLAB_JOBS_MENTOR";
export const GALKLAB_JOB_LOAD_ERROR_MENTOR = "GALKLAB_JOB_LOAD_ERROR_MENTOR";
export const GALKLAB_GET_STUDENT_LIST_MENTOR =
  "GALKLAB_GET_STUDENT_LIST_MENTOR";
export const GALKLAB_SET_STUDENT_LIST_LOADING_MENTOR =
  "GALKLAB_SET_STUDENT_LIST_LOADING_MENTOR";
export const UPDATE_GALK_LAB_JOB_ASSIGN_PORCESSING_MENTOR =
  "UPDATE_GALK_LAB_JOB_ASSIGN_PORCESSING_MENTOR";
export const UPDATE_GALK_LAB_STUDENT_RATING_MENTOR =
  "UPDATE_GALK_LAB_STUDENT_RATING_MENTOR";
export const UPDATE_GALK_LAB_JOB_ASSIGNED_ENGINEER_MENTOR =
  "UPDATE_GALK_LAB_JOB_ASSIGNED_ENGINEER_MENTOR";
export const UPDATE_GALK_LAB_JOB_UNASSIGNED_MENTOR =
  "UPDATE_GALK_LAB_JOB_UNASSIGNED_MENTOR";
export const GALKLAB_ATTENDANCE_UPDATE_MENTOR =
  "GALKLAB_ATTENDANCE_UPDATE_MENTOR";
export const APPROVE_TIMESHEET_WEEKLY_IN_GALKLAB_MENTOR =
  "APPROVE_TIMESHEET_WEEKLY_IN_GALKLAB_MENTOR";
export const UPDATE_TIMESHEET_IN_GALKLAB_JOB_MENTOR =
  "UPDATE_TIMESHEET_IN_GALKLAB_JOB_MENTOR";

// Attendance Reducer
export const GET_GALKLAB_ATTENDANCE = "GET_GALKLAB_ATTENDANCE";
export const GALKLAB_ATTENDANCE_CHANGE_STATE =
  "GALKLAB_ATTENDANCE_CHANGE_STATE";
export const GALKLAB_ATTENDANCE_UPDATE = "GALKLAB_ATTENDANCE_UPDATE";
export const APPROVE_TIMESHEET_WEEKLY_IN_GALKLAB =
  "APPROVE_TIMESHEET_WEEKLY_IN_GALKLAB";

// Types for QuickInterview Module
export const GO_TO_NEXT_WEEK = "GO_TO_NEXT_WEEK";
export const GO_TO_PREVIOUS_WEEK = "GO_TO_PREVIOUS_WEEK";
export const UPDATE_DAYS_OF_WEEK = "UPDATE_DAYS_OF_WEEK";
export const UPDATE_SLOTS_DATA = "UPDATE_SLOTS_DATA";
export const DATA_LOADING = "DATA_LOADING"
export const UPDATE_MEETING_LINK = "UPDATE_MEETING_LINK"
export const MODAL_DISPLAY = "MODAL_DISPLAY"

// Types for EditQuestion Questionnaire Module
export const QUESTIONNAIRE_QUESTIONS_LOADING = "QUESTIONNAIRE_QUESTIONS_LOADING";
export const GET_QUESTIONNAIRE_QUESTIONS = "GET_QUESTIONNAIRE_QUESTIONS";
export const QUESTIONNAIRE_QUESTION_LOAD_ERROR = "QUESTIONNAIRE_QUESTION_LOAD_ERROR";
export const UPDATE_QUESTIONNAIRE_QUESTION = "UPDATE_QUESTIONNAIRE_QUESTION";
export const UPDATE_QUESTIONNAIRE_QUESTION_ERROR = "UPDATE_QUESTIONNAIRE_QUESTION_ERROR";


// Types for EditQuestion auto-screening Module
export const GET_DATA_LOADING_FOR_EDIT_QUESTION = "GET_DATA_LOADING_FOR_EDIT_QUESTION";
export const EDIT_QUESTION_GET_LIST_QUESTION = "EDIT_QUESTION_GET_LIST_QUESTION";
export const EDIT_QUESTION_SET_LIST ="EDIT_QUESTION_SET_LIST";
export const SET_DATA_LOADING_FOR_EDIT_QUESTION ="SET_DATA_LOADING_FOR_EDIT_QUESTION";